//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MostRecentLoggingEvent
    {
        public long ID { get; set; }
        public Nullable<int> AlertSent { get; set; }
        public string TestingHost { get; set; }
        public string TestingUser { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TargetMachine { get; set; }
        public string FeedbackValue { get; set; }
        public Nullable<bool> Successful { get; set; }
        public string FeedbackMessage { get; set; }
        public Nullable<long> ResponseTime { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
