//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDetail
    {
        public int ID { get; set; }
        public string TestDisplayName { get; set; }
        public string TestProtocol { get; set; }
        public string TestDescription { get; set; }
        public string TokenNeeded { get; set; }
        public string TestOptionString { get; set; }
        public string EmailDistributionList { get; set; }
    }
}
